### ISSUE TITLE
在组件中使用了connect，在data中的值不生效

### ISSUE THREAD

**Issue by iweb-wiki** [herculesJS/herculex#4]
在组件中使用connect连接外部数据，此时，组件内部的data的默认值，无法生效,拿不到data中的值

Component(
  connect({})({
    props: {
      placeholder: '',
      maxlength: '140'
    },
    data: {
      time: 5,
      sendMsg: '发送验证码'
    }
}))

**Comment by blizzardzheng** [comment]
@wangpansheng 谢谢反馈，已于 herculex@0.1.6 修复

**Comment by iweb-wiki** [comment]
3Q 问题已经解决
